services:
  mysql-casamento:
    image: mysql:8.0
    container_name: mysql-casamento
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/0_init.sql
      - mysql_casamento_volume:/var/lib/mysql
volumes:
  mysql_casamento_volume:
